### ISSUE TITLE
Cloud Foundry provider not found

### ISSUE THREAD

**Issue by MitchK** [travis-ci/enterprise-installation#10]
Hi,

We are trying to deploy to our internal cloud foundry PaaS.

```
deploy:
  edge: true
  provider:
    provider: cloudfoundry
  api: https://api.cf.mycompany.corp
  username: username
  password:
    secure: xxx
  organization: dev
  space: dev
  on:
    branch: master
    repo: travis/example-nodejs-cf-1
```

We are getting:
```
Installing deploy dependencies
missing provider
failed to deploy
```

Is this a Travis version issue?
